# Generated by Django 5.2.17 on 2026-10-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['display_order', 'id']},
        ),
    ]
